version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: immo_db
      MYSQL_USER: immo_user
      MYSQL_PASSWORD: immo_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mysql_data: